spring:
  application.name: registry
  datasource:
    password: ${DATASOURCE_PASSWORD:example}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yaml

registry:
  api:
    url: ${APPLICATION_REGISTRY_URL:http://localhost:8080}